#!/bin/bash                                                                                          
enabled=`xinput --list-props "DLL06E5:01 06CB:7A13 Touchpad" | grep -e "Device Enabled\ (139):\s*1"`

if [ -n "$enabled" ]; then
    xinput --set-prop "DLL06E5:01 06CB:7A13 Touchpad" "Device Enabled" 0
else
    xinput --set-prop "DLL06E5:01 06CB:7A13 Touchpad" "Device Enabled" 1
fi

